name: Deploy Azure Function App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --only=production

      - name: Zip the function
        run: zip -r function.zip .

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: func-silentcall-prod32667
          package: function.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

