name: Deploy to Azure Function App

on:
  push:
    branches:
      - main  # or your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build (optional)
        run: npm run build



      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: func-silentcall-prod32667
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'
